apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: prod-
commonLabels:
  environment: prod
patches:
  - target:
      kind: Service
      labelSelector: svc=front
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 12345
  - target:
      kind: Deployment
      labelSelector: svc=front
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: prod-flask-app
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: flask
                env:
                  - name: REDIS_HOST
                    value: prod-redis
                  - name: ENV
                    value: PRODUCTION
