apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: promgra
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.0.13
  ports:
    - port: 3456
      targetPort: 3000
      protocol: TCP
  selector:
    io.kompose.service: grafana
